import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import localfont from "next/font/local";

const montrealMedium = localfont({
  src: "../public/fonts/NeueMontreal-Medium.otf",
  variable: "--montrealMedium",
  display: "swap",
});

const montrealRegular = localfont({
  src: "../public/fonts/NeueMontreal-Regular.otf",
  variable: "--montrealRegular",
  display: "swap",
});

const montrealBold = localfont({
  src: "../public/fonts/NeueMontreal-Bold.otf",
  variable: "--montrealBold",
  display: "swap",
});

const montrealLight = localfont({
  src: "../public/fonts/NeueMontreal-Light.otf",
  variable: "--montrealLight",
  display: "swap",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="lemonade">
      <body>
        <main
          className={`${montrealBold.variable} ${montrealMedium.variable} ${montrealRegular.variable}  ${montrealLight.variable} font-sans`}
        >
          {children}
        </main>
      </body>
    </html>
  );
}
